program: preprocessing.preprocess_wearable.embedding.train_embedding_model
command:
  - ${env}
  - ${interpreter}
  - -m
  - ${program}
  - data.undersample_n=125000
  - data.window_size=960
  - ${args_no_hyphens}
method: bayes
metric:
  goal: minimize
  name: test/loss
name: ppg_embedding_TCNAE_2025-02-10
parameters:
  data.stride:
    values:
      - 480
      - 960
  model.dilations:
    values:
      - 8
      - 16
      - 32
      - 64
  model.dropout_rate:
    values:
      - 0
      - 0.05
      - 0.5
      - 0.9
  model.filters_conv1d:
    values:
      - 4
      - 8
      - 16
  model.kernel_size:
    values:
      - 8
      - 16
      - 32
      - 64
  model.latent_sample_rate:
    values:
      - 16
      - 32
      - 64
      - 128
  model.nb_filters:
    values:
      - 8
      - 16
      - 32
      - 64
  model.pooler._target_:
    values:
      - torch.nn.AvgPool1d
      - torch.nn.MaxPool1d
  model.use_norm:
    values:
      - weight_norm
      - layer_norm
      - batch_norm
  train.batch_size:
    values:
      - 16
      - 32
      - 64
      - 128
  train.lr:
    values:
      - 0.05
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
