# Used to translate the drug names from German to English ChatGPT 3.5 used. https://chat.openai.com/share/a0d39794-c53c-42da-b62b-8a44714d2a10
drug_translation = {
    "Kohlenhydrate+Aminosäuren+Fett": "Carbohydrates+Amino acids+Fat",
    "Fall_THDrain_Verlauf_Meng": "Case_THDrain_Course_Amount",
    "Fall_Gastrosonden_Verlauf_Menge": "Case_Gastrostomy_Course_Amount",
    "Fall_Urinableitung_Verlauf_Menge": "Case_Urinary_diversion_Course_Amount",
    "Heparin-Na": "Heparin-Na",
    "Fall_Drainagen_Verlauf_Menge": "Case_Drainage_Course_Amount",
    "Elektrolytlösung": "Electrolyte solution",
    "": "",
    "Phytomenadion": "Phytomenadione",
    "Metamizol 20 mg/ml": "Metamizole 20 mg/ml",
    "Heparin-Na 200 IE/ml": "Heparin-Na 200 IU/ml",
    "Urapidil 5 mg/ml": "Urapidil 5 mg/ml",
    "CO_Bilanz_Einfuhr_oral": "CO balance oral intake",
    "Piperacillin (80 mg/ml) + Tazobactam (10 mg/ml)": "Piperacillin (80 mg/ml) + Tazobactam (10 mg/ml)",
    "Ondansetron": "Ondansetron",
    "fUROsemid 10 mg/ml": "Furosemide 10 mg/ml",
    "Kaliumchlorid 7,45% 1mmol/ml": "Potassium chloride 7.45% 1 mmol/ml",
    "Ascorbins.+div": "Ascorbic acid+div",
    "Humaninsulin 1 IE/ml": "Human insulin 1 IU/ml",
    "Nutrison Peptisorb 1kcal/ml": "Nutrison Peptisorb 1 kcal/ml",
    "Natriumchlorid": "Sodium chloride",
    "Vollelektrolytlösung + Magnesium 8,1 mmol": "Full electrolyte solution + Magnesium 8.1 mmol",
    "Albumin human 0,2 g/ml": "Human albumin 0.2 g/ml",
    "cloNIDin 30 µg/ml": "Clonidine 30 µg/ml",
    "Norepinephrin": "Norepinephrine",
    "Morphin 1 mg/ml": "Morphine 1 mg/ml",
    "fUROsemid 0,4 mg/ml": "Furosemide 0.4 mg/ml",
    "Vancomycin 20 mg/ml": "Vancomycin 20 mg/ml",
    "Pantoprazol 0,8 mg/ml": "Pantoprazole 0.8 mg/ml",
    "Meropenem": "Meropenem",
    "Vancomycin": "Vancomycin",
    "Spurenelemente": "Trace elements",
    "Fall_Drainagen_Verlauf_Spuelloesung_Zulauf": "Case_Drainage_Course_Rinsing_inflow",
    "Vollelektrolytlösung balanciert": "Balanced full electrolyte solution",
    "Morphinsulfat 1mg/ml": "Morphine sulfate 1 mg/ml",
    "Clonidin": "Clonidine",
    "Kaliumchlorid (KCl)": "Potassium chloride (KCl)",
    "Rocuronium": "Rocuronium",
    "Wasser-Vollelektrolyt-Lösung ": "Water-full electrolyte solution",
    "Sufentanil": "Sufentanil",
    "Humaninsulin normal": "Human insulin normal",
    "CO_Bilanz_Ausfuhr_Spontanurin": "CO balance export spontaneous urine",
    "HYDROmorphon 2 mg/ml": "Hydromorphone 2 mg/ml",
    "cloNIDin, 1500 µg/50 ml": "Clonidine, 1500 µg/50 ml",
    "Metronidazol": "Metronidazole",
    "Dexamethason": "Dexamethasone",
    "Cefuroxim": "Cefuroxime",
    "Fentanyl": "Fentanyl",
    "Propofol": "Propofol",
    "Vancomycin 40 mg/ml": "Vancomycin 40 mg/ml",
    "Norepinephrin 100µg/ml": "Norepinephrine 100 µg/ml",
    "Meropenem 20 mg/ml": "Meropenem 20 mg/ml",
    "aMIOdaron 18 mg/ml": "Amiodarone 18 mg/ml",
    "Ondansetron, 4 mg/ml": "Ondansetron, 4 mg/ml",
    "dihydrALAZIN 1 mg/ml": "Dihydralazine 1 mg/ml",
    "Remifentanil": "Remifentanil",
    "Eisen dreiwertig": "Iron trivalent",
    "HYDROmorphon 1 mg/ml": "Hydromorphone 1 mg/ml",
    "Kaliumchlorid": "Potassium chloride",
    "Urapidil": "Urapidil",
    "Norepinephrin 20µg/ml": "Norepinephrine 20 µg/ml",
    "Norepinephrin 200µg/ml": "Norepinephrine 200 µg/ml",
    "Neostigmin 0,02 mg/ml": "Neostigmine 0.02 mg/ml",
    "Glucose (G5) 50mg/ml": "Glucose (G5) 50 mg/ml",
    "G 5": "G 5",
    "Trometamol 3 mmol/ml": "Trometamol 3 mmol/ml",
    "Neostigmin+MetoCloPramid 31,5mg": "Neostigmine+Metoclopramide 31.5 mg",
    "Natriumchlorid 0,9%": "Sodium chloride 0.9%",
    "Piperacillin+Tazobactam 4g+0,5g 4,5g/50ml": "Piperacillin+Tazobactam 4 g+0.5 g 4.5 g/50 ml",
    "Ornithinasparta": "Ornithine aspartate",
    "Wunden_Beschreibung_Wundsekret": "Wounds_Description_Wound secretion",
    "Fall_Urinableitung_Verlauf_Zulauf": "Case_Urinary_diversion_Course_inflow",
    "Elektolyte+Kohlenhydrate+Aminosäuren": "Electrolytes+Carbohydrates+Amino acids",
    "Tee": "Tea",
    "Heparin-Na 100 IE/ml": "Heparin-Na 100 IU/ml",
    "EPINEPHrin 100 µg/mll": "EPINEPHrine 100 µg/ml",
    "Sufentanil 20µg/ml": "Sufentanil 20 µg/ml",
    "Propofol 2%, 20 mg/ml": "Propofol 2%, 20 mg/ml",
    "Digitoxin 0,0025 mg/ml": "Digitoxin 0.0025 mg/ml",
    "Fluconazol 2 mg/ml": "Fluconazole 2 mg/ml",
    "Ceftazidim 20 mg/ml / Avibactam 5 mg/ml": "Ceftazidime 20 mg/ml / Avibactam 5 mg/ml",
    "SUFentanil": "Sufentanil",
    "NaCl 0,9%": "NaCl 0.9%",
    "Caspofungin 0,28 mg/ml": "Caspofungin 0.28 mg/ml",
    "Nutrison Concentrated 2kcal/ml": "Nutrison Concentrated 2 kcal/ml",
    "Esketamin": "Esketamine",
    "Ampicillin 40 mg/ml": "Ampicillin 40 mg/ml",
    "Heparin-Na 250 IE/ml": "Heparin-Na 250 IU/ml",
    "Insulin(normal)": "Insulin (normal)",
    "Patient_ITS_Dialyse_Ausfuhr": "Patient_ITS_Dialysis_export",
    "Morphin": "Morphine",
    "Propofol 1%, 10 mg/ml": "Propofol 1%, 10 mg/ml",
    "Remifentanil 100µg/ml": "Remifentanil 100 µg/ml",
    "DOBUTamin 5mg/ml": "DOBUTamine 5 mg/ml",
    "Cisatracurium": "Cisatracurium",
    "Pantoprazol 1,6 mg/ml": "Pantoprazole 1.6 mg/ml",
    "Parecoxib 0,8 mg/ml": "Parecoxib 0.8 mg/ml",
    "Heparin-Na 5000 IE/ml": "Heparin-Na 5000 IU/ml",
    "Cefepim, 40 mg/ml": "Cefepime, 40 mg/ml",
    "Metronidazol 5 mg/ml": "Metronidazole 5 mg/ml",
    "Meropenem 40 mg/ml": "Meropenem 40 mg/ml",
    "fUROsemid 5 mg/ml": "Furosemide 5 mg/ml",
    "Midazolam 2 mg/ml": "Midazolam 2 mg/ml",
    "Metamizol": "Metamizole",
    "Ceftazidim/Avibactam 2500 mg/100ml": "Ceftazidime/Avibactam 2500 mg/100 ml",
    "Piritramid": "Piritramide",
    "Nutrison Soja 1 kcal/ml": "Nutrison Soy 1 kcal/ml",
    "Ampicillin 20 mg/ml + Sulbactam 10 mg/ml": "Ampicillin 20 mg/ml + Sulbactam 10 mg/ml",
    "Naloxon": "Naloxone",
    "Sugammadex": "Sugammadex",
    "Amphotericin B LIPOSOMAL": "Amphotericin B LIPOSOMAL",
    "esKETAmin 5mg/ml": "Esketamine 5 mg/ml",
    "Kaliumphosphat 1 mmol/ml": "Potassium phosphate 1 mmol/ml",
    "fUROsemid 0,8 mg/ml": "Furosemide 0.8 mg/ml",
    "Fall_Gastrosonden_Verlauf_Spuelloesung_Zulauf": "Fall_Gastrosonden_Verlauf_Spuelloesung_Zulauf",
    "Phytomenadion VitK 0,4 mg/ml": "Phytomenadione VitK 0.4 mg/ml",
    "Tigecyclin 1 mg/ml": "Tigecycline 1 mg/ml",
    "Albumin human": "Human albumin",
    "Glucose (G20) 200mg/ml": "Glucose (G20) 200 mg/ml",
    "Fall_THDrain_Verlauf_Spuelloesung_Zulauf": "Fall_THDrain_Verlauf_Spuelloesung_Zulauf",
    "Morphinsulfat": "Morphine sulfate",
    "Caspofungin 0,5 mg/ml": "Caspofungin 0.5 mg/ml",
    "Linezolid 2 mg/ml": "Linezolid 2 mg/ml",
    "Piritramid 1 mg/ml": "Piritramide 1 mg/ml",
    "Hydromorphon": "Hydromorphone",
    "Dimenhydrinat": "Dimenhydrinate",
    "Glucose": "Glucose",
    "Natriumphosphat 1 mmol/ml": "Sodium phosphate 1 mmol/ml",
    "Dexmedetomidin 16 µg/ml": "Dexmedetomidine 16 µg/ml",
    "Plasma, therapeutisches Einzelspender-": "Plasma, therapeutic single donor",
    "Hydrocortison 2 mg/ml": "Hydrocortisone 2 mg/ml",
    "Sufentanil 5µg/ml": "Sufentanil 5 µg/ml",
    "Vasopressin": "Vasopressin",
    "Cafedrin + Theodrenalin": "Cafedrine + Theodrenaline",
    "Paracetamol 10 mg/ml": "Paracetamol 10 mg/ml",
    "Amphotericin B LIPOSOMAL, 2 mg/ml Glc 5%": "Amphotericin B LIPOSOMAL, 2 mg/ml Glucose 5%",
    "Fresubin Energy 1,5 kcal/ml": "Fresubin Energy 1.5 kcal/ml",
    "Nutrison 1kcal/ml": "Nutrison 1 kcal/ml",
    "Dexmedetomidin 8 µg/ml": "Dexmedetomidine 8 µg/ml",
    "Erythrozytenkonzentrat (EK)": "Erythrocyte concentrate (EK)",
    "Iloprost": "Iloprost",
    "Kalziumglukonat": "Calcium gluconate",
    "Butylscopolamin": "Butylscopolamine",
    "Hydrocortison 4 mg/ml": "Hydrocortisone 4 mg/ml",
    "Sufentanil 10µg/ml": "Sufentanil 10 µg/ml",
    "Dimetindenmaleat": "Dimethindene maleate",
    "Somatostatin": "Somatostatin",
    "CO_Bilanz_Ausfuhr_Stuhlgang": "CO balance export stool",
    "Ceftolozan/Tazobactam 1g+0,5g 1,5g/100ml": "Ceftolozane/Tazobactam 1 g+0.5 g 1.5 g/100 ml",
    "Ceftazidim 40 mg/ml": "Ceftazidime 40 mg/ml",
    "Argipressin": "Argipressin",
    "Piperacillin + Tazobactam": "Piperacillin + Tazobactam",
    "Ropivacain + Sufentanil": "Ropivacaine + Sufentanil",
    "Neostigmin+MetoCloPramid 63mg": "Neostigmine+Metoclopramide 63 mg",
    "Nutrison Protein Advance 1,28 kcal/ml": "Nutrison Protein Advance 1.28 kcal/ml",
    "Imipenem+Cilastatin 10 mg + 10 mg/ml ": "Imipenem+Cilastatin 10 mg + 10 mg/ml",
    "Wasser": "Water",
    "Esmolol 50mg/ml": "Esmolol 50 mg/ml",
    "Erythromycin 50 mg/ml": "Erythromycin 50 mg/ml",
    "Heparin-Na 400 IE/ml": "Heparin-Na 400 IU/ml",
    "Metamizol 500 mg/ml": "Metamizole 500 mg/ml",
    "Ciclosporin": "Cyclosporine",
    "PIPeracillin/TAZobactam _4g+0,5g": "Piperacillin/TAZobactam 4 g+0.5 g",
    "Acetylsalicylsä": "Acetylsalicylic acid",
    "Hydrokortison": "Hydrocortisone",
    "Nutrison Protein Plus 1,28 kcal/ml": "Nutrison Protein Plus 1.28 kcal/ml",
    "ROPIvacain 2 mg/ml": "Ropivacaine 2 mg/ml",
    "Valproinsäure 2,4mg/ml": "Valproic acid 2.4 mg/ml",
    "Piperacillin 0,08 g/ml": "Piperacillin 0.08 g/ml",
    "Ropivacain": "Ropivacaine",
    "Erythromycin 250mg/50ml": "Erythromycin 250 mg/50 ml",
    "Morphinsulfat 4mg/ml": "Morphine sulfate 4 mg/ml",
    "Heparin-Na 500 IE/ml": "Heparin-Na 500 IU/ml",
    "Ornithinaspartat 500 mg/ml": "Ornithine aspartate 500 mg/ml",
    "Thiamin 50mg/ml": "Thiamine 50 mg/ml",
    "Acetylcystein": "Acetylcysteine",
    "Trimeth+Sulfame": "Trimethoprim+Sulfamethoxazole",
    "Glucose (G40) 400mg/ml": "Glucose (G40) 400 mg/ml",
    "FFP": "Fresh frozen plasma",
    "Ampicillin+Sulbactam 2g+1g 3g/100ml": "Ampicillin+Sulbactam 2 g+1 g 3 g/100 ml",
    "Cefuroxim 30 mg/ml": "Cefuroxime 30 mg/ml",
    "Pantoprazol": "Pantoprazole",
    "Furosemid": "Furosemide",
    "Morphinsulfat 2mg/ml": "Morphine sulfate 2 mg/ml",
    "Ibuprofen": "Ibuprofen",
    "Metamizol 1000 mg/50 ml": "Metamizole 1000 mg/50 ml",
    "Ampicillin+Sulbactam": "Ampicillin+Sulbactam",
    "Trometamol": "Trometamol",
    "ACC 100 mg/ml": "ACC 100 mg/ml",
    "Natriumbicarbonat 8,4%, 84 mg/ml": "Sodium bicarbonate 8.4%, 84 mg/ml",
    "Midazolam": "Midazolam",
    "Ceftriaxon 40 mg/ml": "Ceftriaxone 40 mg/ml",
    "Iloprost 0,8µg/ml": "Iloprost 0.8 µg/ml",
    "Dexmedetomidin 400µg/50ml": "Dexmedetomidine 400 µg/50 ml",
    "Bridion 200mg/2ml 10 Amp SA": "Bridion 200 mg/2 ml 10 Amp SA",
    "Manna+Feigenext": "Manna+Fig extract",
    "Argatroban 0,5 mg/ml": "Argatroban 0.5 mg/ml",
    "Amitriptylin": "Amitriptyline",
    "Kaliumphosphat": "Potassium phosphate",
    "Ertapenem 20 mg/ml": "Ertapenem 20 mg/ml",
    "MetoCloPramid 5 mg/ml": "Metoclopramide 5 mg/ml",
    "Vitamin K, 0,4 mg/ml": "Vitamin K, 0.4 mg/ml",
    "Enoximon 2 mg/ml": "Enoximon 2 mg/ml",
    "Thiamin": "Thiamine",
    "cloNIDin 750µg/50ml": "Clonidine 750 µg/50 ml",
    "Cotrimoxazol 3,84 mg/ml": "Cotrimoxazole 3.84 mg/ml",
    "cloNIDin 15 µg/ml": "Clonidine 15 µg/ml",
    "Calciumchlorid": "Calcium chloride",
    "Argipressin 1E/ml": "Argipressin 1 IU/ml",
    "Kaliumphosphat 0,6 mmol/ml": "Potassium phosphate 0.6 mmol/ml",
    "Dihydralazin": "Dihydralazine",
    "Flucloxacillin 40 mg/ml": "Flucloxacillin 40 mg/ml",
    "Daptomycin 15 mg/ml": "Daptomycin 15 mg/ml",
    "CO_Bilanz_Ausfuhr_Reflux": "CO_Balance_Export_Reflux",
    "Glukose 5%": "Glucose 5%",
    "Magnesium": "Magnesium",
    "HYDROmorphon 0,2 mg/ml": "Hydromorphone 0.2 mg/ml",
    "Humaninsulin": "Human insulin",
    "Ondansetron, 4 mg/2ml": "Ondansetron 4 mg/2 ml",
    "Glyceroltrinitr": "Glyceroltrinitrate",
    "Dalteparin": "Dalteparin",
    "Kaliumcanrenoat 20 mg/ml": "Potassium canrenoate 20 mg/ml",
    "Tranexamsäure 100mg/ml": "Tranexamic acid 100 mg/ml",
    "Magnesiumsulfat 10%, 100 mg/ml": "Magnesium sulfate 10%, 100 mg/ml",
    "cloNIDin 150 µg/ml": "Clonidine 150 µg/ml",
    "Haloperidol 0,5 mg/ml": "Haloperidol 0.5 mg/ml",
    "Cefepim": "Cefepime",
    "Heparin": "Heparin",
    "Voriconazol 2 mg/ml": "Voriconazole 2 mg/ml",
    "Norepinephrin 10mg/50ml": "Norepinephrine 10 mg/50 ml",
    "Kaliumchlorid 7": "Potassium chloride 7",
    "Macrogol (Klean-Prep)": "Macrogol (Klean-Prep)",
    "Mivacurium": "Mivacurium",
    "Cernevit": "Cernevit",
    "Methylprednisolon 250mg/10ml": "Methylprednisolone 250 mg/10 ml",
    "Atropin": "Atropine",
    "Enoximon": "Enoximon",
    "Cefazolin 40 mg/ml": "Cefazolin 40 mg/ml",
    "Meronem": "Meronem",
    "Clindamycin": "Clindamycin",
    "Suxamethonium": "Suxamethonium",
    "Lormetazepam 0,2 mg/ml": "Lormetazepam 0.2 mg/ml",
    "Haloperidol 1 mg/ml": "Haloperidol 1 mg/ml",
    "Lorazepam": "Lorazepam",
    "LORazepam 0,2mg/ml": "Lorazepam 0.2 mg/ml",
    "Macrogol (Movicol)": "Macrogol (Movicol)",
    "dihydrALAZIN 2 mg/ml": "Dihydralazine 2 mg/ml",
    "levETIRAcetam 10 mg/ml": "Levetiracetam 10 mg/ml",
    "Citalopram": "Citalopram",
    "Paracetamol": "Paracetamol",
    "Parecoxib": "Parecoxib",
    "Propofol 1% 10 mg/ml": "Propofol 1% 10 mg/ml",
    "Droperidol": "Droperidol",
    "Cimetidin": "Cimetidine",
    "Diazepam 5 mg/ml": "Diazepam 5 mg/ml",
    "Physostigminsal": "Physostigmine",
    "Tranexamsäure": "Tranexamic acid",
    "Natriumhydrogenkarbonat": "Sodium bicarbonate",
    "Clindamycin 12 mg/ml": "Clindamycin 12 mg/ml",
    "Magnesiumsulfat 10mg/ml": "Magnesium sulfate 10 mg/ml",
    "Indocyaningrün": "Indocyanine green",
    "Nutrison Advanced Peptisorb 500ml 8 Btl.": "Nutrison Advanced Peptisorb 500 ml 8 Btl.",
    "Natriumbicarbonat": "Sodium bicarbonate",
    "Kalziumchlorid": "Calcium chloride",
    "Lidocain": "Lidocaine",
    "Imipenem+Cilastatin": "Imipenem+Cilastatin",
    "Ciprofloxacin 2 mg/ml": "Ciprofloxacin 2 mg/ml",
    "Aztreonam 20 mg/ml": "Aztreonam 20 mg/ml",
    "Tigecyclin 100mg/50ml": "Tigecycline 100 mg/50 ml",
    "Epinephrin": "Epinephrine",
    "Fosfomycin": "Fosfomycin",
    "Neostigmin 0,5 mg/ml": "Neostigmine 0.5 mg/ml",
    "Thrombozytenkonzentrat, Apherese-": "Platelet concentrate, Apheresis-",
    "Ephedrin": "Ephedrine",
    "Argatroban 1mg/ml": "Argatroban 1 mg/ml",
    "Magnesiumsulfat": "Magnesium sulfate",
    "Neostigmin 0,01 mg/ml": "Neostigmine 0.01 mg/ml",
    "Morphinsulfat 10 mg/10 ml": "Morphine sulfate 10 mg/10 ml",
    "Magnesium 5-Sulfat": "Magnesium sulfate",
    "prednisoLON 2mg/ml": "Prednisolone 2 mg/ml",
    "Glucose (G10) 100mg/ml": "Glucose (G10) 100 mg/ml",
    "Imipenem+Cilastatin 1000+1000mg/200ml": "Imipenem+Cilastatin 1000+1000 mg/200 ml",
    "Norepinephrin 60µg/ml": "Norepinephrine 60 µg/ml",
    "levETIRAcetam 100 mg/ml": "Levetiracetam 100 mg/ml",
    "Caspofungin": "Caspofungin",
    "GlycerolTriNitrat 1mg/ml": "Glycerol trinitrate 1 mg/ml",
    "MetoCloPramid+Neostigmin 60mg+3mg": "Metoclopramide+Neostigmine 60 mg+3 mg",
    "Thrombozytenkonzentrat": "Platelet concentrate",
    "Prednisolon": "Prednisolone",
    "Na-thiosulfat_25%": "Sodium thiosulfate 25%",
    "Argatroban 50mg/50ml": "Argatroban 50 mg/50 ml",
    "Diazepam 10mg/ml": "Diazepam 10 mg/ml",
    "Terlipressin 0,85mg/8,5ml": "Terlipressin 0.85 mg/8.5 ml",
    "Methylprednisol": "Methylprednisolone",
    "Landiolol 6mg/ml": "Landiolol 6 mg/ml",
    "Levofloxacin 5 mg/ml": "Levofloxacin 5 mg/ml",
    "Fresubin Hepa N": "Fresubin Hepa N",
    "Metoprolol 1 mg/ml": "Metoprolol 1 mg/ml",
    "Hydrocortison": "Hydrocortisone",
    "Thiopental": "Thiopental",
    "Glyzeroltrinitrat": "Glyceryl trinitrate",
    "Linezolid": "Linezolid",
    "Fresubin HP 2 kcal/ml": "Fresubin HP 2 kcal/ml",
    "Ambroxol 20 mg/ml": "Ambroxol 20 mg/ml",
    "Di-/Natriumhydrogen": "Di-/Sodium hydrogen",
    "Simeticon": "Simethicone",
    "G 10": "G 10",
    "Trometamol (TRIS)": "Tromethamine (TRIS)",
    "Dimetindenmaleat 1 mg/ml": "Dimethindene maleate 1 mg/ml",
    "Calciumgluconat 10%": "Calcium gluconate 10%",
    "Natriumcitrat_4%": "Sodium citrate 4%",
    "Natriumthiosulfat 10% 100 mg/ml": "Sodium thiosulfate 10% 100 mg/ml",
    "aMIOdaron 6 mg/ml": "Amiodarone 6 mg/ml",
    "Dexmedetomidin": "Dexmedetomidine",
    "Cefazolin": "Cefazolin",
    "Methylenblau": "Methylene blue",
    "Ceftriaxon 1 g/50 ml": "Ceftriaxone 1 g/50 ml",
    "Antithrombin III 50 IE/ml": "Antithrombin III 50 IU/ml",
    "Gerinnungsfaktoren II/VII/IX/X": "Coagulation factors II/VII/IX/X",
    "Cefotaxim 40 mg/ml": "Cefotaxime 40 mg/ml",
    "Levosimendan 12,5 mg / 250 ml G5%": "Levosimendan 12.5 mg / 250 ml G5%",
    "Natriumhydrogen": "Sodium hydrogen",
    "Erythrozytenkonzentrat 310 ml": "Red blood cell concentrate 310 ml",
    "Metoclopramid": "Metoclopramide",
    "Humaninsulin normal 100IE/50ml": "Human insulin normal 100 IU/50 ml",
    "Risperidon 1mg/ml": "Risperidone 1 mg/ml",
    "Flucloxacillin": "Flucloxacillin",
    "Metoprolol": "Metoprolol",
    "Glukose": "Glucose",
    "G 20": "G 20",
    "Glucose (G50) 500mg/ml": "Glucose (G50) 500 mg/ml",
    "Daptomycin 10 mg/ml": "Daptomycin 10 mg/ml",
    "Ketamin": "Ketamine",
    "Magnesiumsulfat 20mg/ml": "Magnesium sulfate 20 mg/ml",
    "Ciprofloxacin": "Ciprofloxacin",
    "Fosaprepitant": "Fosaprepitant",
    "Ceftriaxon": "Ceftriaxone",
    "Spironolacton": "Spironolactone",
    "Trometamol 1 mmol/ml": "Tromethamine 1 mmol/ml",
    "Vancomycin 5 mg/ml": "Vancomycin 5 mg/ml",
    "Vecuronium": "Vecuronium",
    "DimenhyDRINAT 62 mg": "Dimenhydrinate 62 mg",
    "Natriumchlorid 5,85% 1mmol/ml": "Sodium chloride 5.85% 1 mmol/ml",
    "DimenhyDRINAT 6,2 mg/ml": "Dimenhydrinate 6.2 mg/ml",
    "Rocuroniumbromi": "Rocuronium bromide",
    "Lormetazepam": "Lormetazepam",
    "Fibrinogen": "Fibrinogen",
    "Clarithromycin 2 mg/ml": "Clarithromycin 2 mg/ml",
    "Cafedrin+Theodrenalin (21 mg/ml) (Akrinor)": "Cafedrine + Theodrenaline (21 mg/ml) (Akrinor)",
    "Gelatine": "Gelatin",
    "Erythrozytenkonzentrat bestr.  310 ml": "Red blood cell concentrate 310 ml",
    "ROCuronium 10 mg/ml": "Rocuronium 10 mg/ml",
    "Faktor II/VII/I": "Factor II/VII/I",
    "aMIOdaron 3 mg/ml": "Amiodarone 3 mg/ml",
    "Insulin Actraphane 100IE/ml": "Insulin Actraphane 100 IU/ml",
    "Methylpredinisolon": "Methylprednisolone",
    "Ondansetron, 8 mg/4ml": "Ondansetron, 8 mg/4 ml",
    "Amiodaron": "Amiodarone",
    "Ceftriaxon 2 g/50 ml": "Ceftriaxone 2 g/50 ml",
    "Moxifloxazin": "Moxifloxacin",
    "Phytomenadion VitK 10 mg/ml": "Phytomenadione VitK 10 mg/ml",
    "Naloxon 40 µg/ml": "Naloxone 40 µg/ml",
    "Mannitol": "Mannitol",
    "Lacosamid 0,8mg/ml": "Lacosamide 0.8 mg/ml",
    "levETIRAcetam 150 mg/ml": "Levetiracetam 150 mg/ml",
    "Dexmedetomidin 800µg/50ml": "Dexmedetomidine 800 µg/50 ml",
    "Fortimel Energy 1,5 kcal/ml": "Fortimel Energy 1.5 kcal/ml",
    "Voriconazol 4 mg/ml": "Voriconazole 4 mg/ml",
    "Melperon 5mg/ml": "Melperone 5 mg/ml",
    "Pipamperon 4 mg/ml": "Pipamperone 4 mg/ml",
    "Natriumpicosulfat": "Sodium picosulfate",
    "Diazepam 1 mg/ml": "Diazepam 1 mg/ml",
    "Ibandronsäure": "Ibandronic acid",
    "Methylprednisolon 500mg/10ml": "Methylprednisolone 500 mg/10 ml",
    "Vollelektrolytlösung + Magnesium 4,05 mmol": "Full electrolyte solution + Magnesium 4.05 mmol",
    "Patient_ITS_Dialyse_Einfuhr": "Patient ITS Dialysis Intake",
    "Norepinephrin 1000µg/ml": "Norepinephrine 1000 µg/ml",
    "Tranexamsäure 20 mg/ml": "Tranexamic acid 20 mg/ml",
    "Desmopressin 0,4µg/ml": "Desmopressin 0.4 µg/ml",
    "Phytomenadion 0,4 mg/ml": "Phytomenadione 0.4 mg/ml",
    "Tobramycin 1,6 mg/ml": "Tobramycin 1.6 mg/ml",
    "Calciumgluconat": "Calcium gluconate",
    "Methylnaltrexonium": "Methylnaltrexonium",
    "Wasser für": "Water for",
    "Lormetazepam 0,04 mg/ml": "Lormetazepam 0.04 mg/ml",
    "NaCl 0,9% 500 m": "NaCl 0.9% 500 m",
    "Thrombozytenkonzentrat, Pool- ": "Platelet concentrate, pooled",
    "Thrombozytenkonzentrat, bestr.": "Platelet concentrate, best.",
    "Vollelektrolytlösung": "Full electrolyte solution",
    "Vitamin K1 (Phytomenadion)": "Vitamin K1 (Phytomenadione)",
    "Nitroprussidnatrium 1mg/ml": "Sodium nitroprusside 1 mg/ml",
    "Clarithromycin": "Clarithromycin",
    "Polystyroldivinylbenzolsulfonsäure (Resonium)": "Polystyrene divinylbenzene sulfonic acid (Resonium)",
    "MetoCloPramid+Neostigmin 90mg+4,5mg": "Metoclopramide + Neostigmine 90 mg + 4.5 mg",
    "Phytomenadion VitK 0,2 mg/ml": "Phytomenadione VitK 0.2 mg/ml",
    "Fosfomycin 50 mg/ml": "Fosfomycin 50 mg/ml",
    "Trometamol (TRIS) 60mmol/40ml peripher": "Tromethamine (TRIS) 60 mmol/40 ml peripher",
    "Haloperidol 2 mg/ml": "Haloperidol 2 mg/ml",
    "Ganciclovir 10 mg / ml": "Ganciclovir 10 mg/ml",
    "Vitamin K, 10 mg/ml": "Vitamin K, 10 mg/ml",
    "Magnesiumaspart": "Magnesium aspartate",
    "DEXAmethason 4 mg/ml": "Dexamethasone 4 mg/ml",
    "Metoclopramid+Neostigmin": "Metoclopramide + Neostigmine",
    "Basiliximab": "Basiliximab",
    "aMIOdaron 50 mg/ml": "Amiodarone 50 mg/ml",
    "Indozyaningrün (ICG)": "Indocyanine green (ICG)",
    "Methylprednisolon 1000mg/10ml": "Methylprednisolone 1000 mg/10 ml",
    "Immunglobulin 0,1g/ml": "Immunoglobulin 0.1 g/ml",
    "Cafedrin+Theodrenalin_200/10mg": "Cafedrine + Theodrenaline 200/10 mg",
    "Haloperidol": "Haloperidol",
    "Pethidin": "Pethidine",
    "Insulin(Normal) 100 i.E./ml": "Insulin (Normal) 100 IU/ml",
    "Antithrombin III": "Antithrombin III",
    "Ambroxol 3mg/ml": "Ambroxol 3 mg/ml",
    "Flumazenil": "Flumazenil",
    "Fludarabin": "Fludarabine",
    "Fresubin_Soya": "Fresubin Soya",
    "Vitamin K 10 mg/ml": "Vitamin K 10 mg/ml",
    "Aztreonam": "Aztreonam",
    "Dobutamin": "Dobutamine",
    "Tigecyclin 2 mg/ml": "Tigecycline 2 mg/ml",
    "Ceftazidim": "Ceftazidime",
    "Mannitol 20%, 200 mg/ml": "Mannitol 20%, 200 mg/ml",
    "Fluorescein": "Fluorescein",
    "Hepatitis-B-Ig": "Hepatitis B Ig",
    "Digitoxin 0,001 mg/ml": "Digitoxin 0.001 mg/ml",
    "Magnesiumsulfat 2mg/ml": "Magnesium sulfate 2 mg/ml",
    "Prothrombinkomplex (PPSB)": "Prothrombin complex (PPSB)",
    "Natriumphosphat": "Sodium phosphate",
    "Plasma, lyophilisiertes Human- ": "Plasma, lyophilized human-",
    "Oxytocin": "Oxytocin",
    "Glycopyrronium 0,2 mg/ml": "Glycopyrronium 0.2 mg/ml",
    "Clemastin": "Clemastine",
    "CO_Bilanz_Ausfuhr_Punktion": "CO balance export puncture",
    "Gentamicin 200mg/50ml": "Gentamicin 200 mg/50 ml",
    "Cyanocobalamin": "Cyanocobalamin",
    "ASS 2mg/ml": "Aspirin 2 mg/ml",
    "Protamin": "Protamine",
    "Promethazin": "Promethazine",
    "ASS 50 mg/ml": "Aspirin 50 mg/ml",
    "Parecoxib 4mg/ml": "Parecoxib 4 mg/ml",
    "Natriumperchlor": "Sodium perchlorate",
    "Fortimel Jucy 1,5 kcal/ml": "Fortimel Jucy 1.5 kcal/ml",
    "Esmolol": "Esmolol",
    "LORazepam 2 mg/ml": "Lorazepam 2 mg/ml",
    "Prednisolon 100mg/10ml": "Prednisolone 100 mg/10 ml",
    "LORazepam": "Lorazepam",
    "Tobramycin 4,2 mg/ml": "Tobramycin 4.2 mg/ml",
    "methylPREDNISolon 2mg/ml": "Methylprednisolone 2 mg/ml",
    "Pasireotid": "Pasireotide",
    "Valproinsäure 600mg/250ml": "Valproic acid 600 mg/250 ml",
    "Erythropoetin b": "Erythropoietin b",
    "DEXAmethason 0,8mg/ml": "Dexamethasone 0.8 mg/ml",
    "Gentamicin 5 mg/ml": "Gentamicin 5 mg/ml",
    "Digitoxin": "Digitoxin",
    "Remdesivir 0,8mg/ml": "Remdesivir 0.8 mg/ml",
    "prednisoLON 1mg/ml": "Prednisolone 1 mg/ml",
    "esKETAmin 25mg/ml": "Ketamine 25 mg/ml",
    "Azithromycin 500mg/250ml": "Azithromycin 500 mg/250 ml",
    "Remdesivir 0,4 mg/ml": "Remdesivir 0.4 mg/ml",
    "Phenytoin": "Phenytoin",
    "KETAmin 50 mg/ml": "Ketamine 50 mg/ml",
    "Thiamazol": "Thiamazole",
    "Adenosin": "Adenosine",
    "Midazolam 5 mg/ml": "Midazolam 5 mg/ml",
    "VitaminK 10 mg/ml": "Vitamin K 10 mg/ml",
    "Ioxitalaminsäur": "Ioxitalamic acid",
    "Loperamid ": "Loperamide",
    "Ertapenem": "Ertapenem",
    "Cotrimoxazol 7,68 mg/ml": "Trimethoprim/sulfamethoxazole 7.68 mg/ml",
    "Atropin 0,5 mg/ml": "Atropine 0.5 mg/ml",
    "Ampicillin 80 mg/ml": "Ampicillin 80 mg/ml",
    "Phenylephrin": "Phenylephrine",
    "Faktor XIII": "Factor XIII",
    "Metamizol 500 mg/50 ml": "Metamizole 500 mg/50 ml",
    "Ranitidin": "Ranitidine",
    "Glucagon": "Glucagon",
    "Na-thiosulfat_10%": "Sodium thiosulfate 10%",
    "Physostigmin": "Physostigmine",
    "Naloxon 0,4 mg/ml": "Naloxone 0.4 mg/ml",
    "Colistin 3 MioIE/50ml": "Colistin 3 million IU/50 ml",
    "Lactulose": "Lactulose",
    "Ursodeoxycholsäure": "Ursodeoxycholic acid",
    "HYDROmorphon": "Hydromorphone",
    "G 40": "G 40",
    "prednisoLON 50 mg/ml": "Prednisolone 50 mg/ml",
    "Fortimel Jucy 2": "Fortimel Jucy 2",
    "Levothyroxin": "Levothyroxine",
    "Methylthioninium": "Methylthioninium",
    "Alfentanil": "Alfentanil",
    "Glycopyrroniumb": "Glycopyrronium",
    "Nitrendipin": "Nitrendipine",
    "Folsäure": "Folic acid",
    "Acetazolamid": "Acetazolamide",
    "Tracutil": "Tracutil",
    "Insulin (human)": "Insulin (human)",
    "Levetiracetam": "Levetiracetam",
    "Vitamin K, 0,2 mg/ml": "Vitamin K, 0.2 mg/ml",
    "Mannitol 15%, 150 mg/ml": "Mannitol 15%, 150 mg/ml",
    "Daptomycin": "Daptomycin",
    "clonazePAM 0,2mg/ml": "Clonazepam 0.2 mg/ml",
    "Thiamazol (40 mg/ml)": "Thiamazole 40 mg/ml",
    "EPINEPHrin 100 µg/ml": "Epinephrine 100 µg/ml",
    "Hydrokortison 50mg/ml": "Hydrocortisone 50 mg/ml",
    "Valproinsäure": "Valproic acid",
    "prednisoLON 100 mg/ml": "Prednisolone 100 mg/ml",
    "Tramadol": "Tramadol",
    "Orciprenalin": "Orciprenaline",
}

original = [
    "Kohlenhydrate+Aminosäuren+Fett",
    "Fall_THDrain_Verlauf_Meng",
    "Fall_Gastrosonden_Verlauf_Menge",
    "Fall_Urinableitung_Verlauf_Menge",
    "Heparin-Na",
    "Fall_Drainagen_Verlauf_Menge",
    "Elektrolytlösung",
    "",
    "Phytomenadion",
    "Metamizol 20 mg/ml",
    "Heparin-Na 200 IE/ml",
    "Urapidil 5 mg/ml",
    "CO_Bilanz_Einfuhr_oral",
    "Piperacillin (80 mg/ml) + Tazobactam (10 mg/ml)",
    "Ondansetron",
    "fUROsemid 10 mg/ml",
    "Kaliumchlorid 7,45% 1mmol/ml",
    "Ascorbins.+div",
    "Humaninsulin 1 IE/ml",
    "Nutrison Peptisorb 1kcal/ml",
    "Natriumchlorid",
    "Vollelektrolytlösung + Magnesium 8,1 mmol",
    "Albumin human 0,2 g/ml",
    "cloNIDin 30 µg/ml",
    "Norepinephrin",
    "Morphin 1 mg/ml",
    "fUROsemid 0,4 mg/ml",
    "Vancomycin 20 mg/ml",
    "Pantoprazol 0,8 mg/ml",
    "Meropenem",
    "Vancomycin",
    "Spurenelemente",
    "Fall_Drainagen_Verlauf_Spuelloesung_Zulauf",
    "Vollelektrolytlösung balanciert",
    "Morphinsulfat 1mg/ml",
    "Clonidin",
    "Kaliumchlorid (KCl)",
    "Rocuronium",
    "Wasser-Vollelektrolyt-Lösung ",
    "Sufentanil",
    "Humaninsulin normal",
    "CO_Bilanz_Ausfuhr_Spontanurin",
    "HYDROmorphon 2 mg/ml",
    "cloNIDin, 1500 µg/50 ml",
    "Metronidazol",
    "Dexamethason",
    "Cefuroxim",
    "Fentanyl",
    "Propofol",
    "Vancomycin 40 mg/ml",
    "Norepinephrin 100µg/ml",
    "Meropenem 20 mg/ml",
    "aMIOdaron 18 mg/ml",
    "Ondansetron, 4 mg/ml",
    "dihydrALAZIN 1 mg/ml",
    "Remifentanil",
    "Eisen dreiwertig",
    "HYDROmorphon 1 mg/ml",
    "Kaliumchlorid",
    "Urapidil",
    "Norepinephrin 20µg/ml",
    "Norepinephrin 200µg/ml",
    "Neostigmin 0,02 mg/ml",
    "Glucose (G5) 50mg/ml",
    "G 5",
    "Trometamol 3 mmol/ml",
    "Neostigmin+MetoCloPramid 31,5mg",
    "Natriumchlorid 0,9%",
    "Piperacillin+Tazobactam 4g+0,5g 4,5g/50ml",
    "Ornithinasparta",
    "Wunden_Beschreibung_Wundsekret",
    "Fall_Urinableitung_Verlauf_Zulauf",
    "Elektolyte+Kohlenhydrate+Aminosäuren",
    "Tee",
    "Heparin-Na 100 IE/ml",
    "EPINEPHrin 100 µg/mll",
    "Sufentanil 20µg/ml",
    "Propofol 2%, 20 mg/ml",
    "Digitoxin 0,0025 mg/ml",
    "Fluconazol 2 mg/ml",
    "Ceftazidim 20 mg/ml / Avibactam 5 mg/ml",
    "SUFentanil",
    "NaCl 0,9%",
    "Caspofungin 0,28 mg/ml",
    "Nutrison Concentrated 2kcal/ml",
    "Esketamin",
    "Ampicillin 40 mg/ml",
    "Heparin-Na 250 IE/ml",
    "Insulin(normal)",
    "Patient_ITS_Dialyse_Ausfuhr",
    "Morphin",
    "Propofol 1%, 10 mg/ml",
    "Remifentanil 100µg/ml",
    "DOBUTamin 5mg/ml",
    "Cisatracurium",
    "Pantoprazol 1,6 mg/ml",
    "Parecoxib 0,8 mg/ml",
    "Heparin-Na 5000 IE/ml",
    "Cefepim, 40 mg/ml",
    "Metronidazol 5 mg/ml",
    "Meropenem 40 mg/ml",
    "fUROsemid 5 mg/ml",
    "Midazolam 2 mg/ml",
    "Metamizol",
    "Ceftazidim/Avibactam 2500 mg/100ml",
    "Piritramid",
    "Nutrison Soja 1 kcal/ml",
    "Ampicillin 20 mg/ml + Sulbactam 10 mg/ml",
    "Naloxon",
    "Sugammadex",
    "Amphotericin B LIPOSOMAL",
    "esKETAmin 5mg/ml",
    "Kaliumphosphat 1 mmol/ml",
    "fUROsemid 0,8 mg/ml",
    "Fall_Gastrosonden_Verlauf_Spuelloesung_Zulauf",
    "Phytomenadion VitK 0,4 mg/ml",
    "Tigecyclin 1 mg/ml",
    "Albumin human",
    "Glucose (G20) 200mg/ml",
    "Fall_THDrain_Verlauf_Spuelloesung_Zulauf",
    "Morphinsulfat",
    "Caspofungin 0,5 mg/ml",
    "Linezolid 2 mg/ml",
    "Piritramid 1 mg/ml",
    "Hydromorphon",
    "Dimenhydrinat",
    "Glucose",
    "Natriumphosphat 1 mmol/ml",
    "Dexmedetomidin 16 µg/ml",
    "Plasma, therapeutisches Einzelspender-",
    "Hydrocortison 2 mg/ml",
    "Sufentanil 5µg/ml",
    "Vasopressin",
    "Cafedrin + Theodrenalin",
    "Paracetamol 10 mg/ml",
    "Amphotericin B LIPOSOMAL, 2 mg/ml Glc 5%",
    "Fresubin Energy 1,5 kcal/ml",
    "Nutrison 1kcal/ml",
    "Dexmedetomidin 8 µg/ml",
    "Erythrozytenkonzentrat (EK)",
    "Iloprost",
    "Kalziumglukonat",
    "Butylscopolamin",
    "Hydrocortison 4 mg/ml",
    "Sufentanil 10µg/ml",
    "Dimetindenmaleat",
    "Somatostatin",
    "CO_Bilanz_Ausfuhr_Stuhlgang",
    "Ceftolozan/Tazobactam 1g+0,5g 1,5g/100ml",
    "Ceftazidim 40 mg/ml",
    "Argipressin",
    "Piperacillin + Tazobactam",
    "Ropivacain + Sufentanil",
    "Neostigmin+MetoCloPramid 63mg",
    "Nutrison Protein Advance 1,28 kcal/ml",
    "Imipenem+Cilastatin 10 mg + 10 mg/ml ",
    "Wasser",
    "Esmolol 50mg/ml",
    "Erythromycin 50 mg/ml",
    "Heparin-Na 400 IE/ml",
    "Metamizol 500 mg/ml",
    "Ciclosporin",
    "PIPeracillin/TAZobactam _4g+0,5g",
    "Acetylsalicylsä",
    "Hydrokortison",
    "Nutrison Protein Plus 1,28 kcal/ml",
    "ROPIvacain 2 mg/ml",
    "Valproinsäure 2,4mg/ml",
    "Piperacillin 0,08 g/ml",
    "Ropivacain",
    "Erythromycin 250mg/50ml",
    "Morphinsulfat 4mg/ml",
    "Heparin-Na 500 IE/ml",
    "Ornithinaspartat 500 mg/ml",
    "Thiamin 50mg/ml",
    "Acetylcystein",
    "Trimeth+Sulfame",
    "Glucose (G40) 400mg/ml",
    "FFP",
    "Ampicillin+Sulbactam 2g+1g 3g/100ml",
    "Cefuroxim 30 mg/ml",
    "Pantoprazol",
    "Furosemid",
    "Morphinsulfat 2mg/ml",
    "Ibuprofen",
    "Metamizol 1000 mg/50 ml",
    "Ampicillin+Sulbactam",
    "Trometamol",
    "ACC 100 mg/ml",
    "Natriumbicarbonat 8,4%, 84 mg/ml",
    "Midazolam",
    "Ceftriaxon 40 mg/ml",
    "Iloprost 0,8µg/ml",
    "Dexmedetomidin 400µg/50ml",
    "Bridion 200mg/2ml 10 Amp SA",
    "Manna+Feigenext",
    "Argatroban 0,5 mg/ml",
    "Amitriptylin",
    "Kaliumphosphat",
    "Ertapenem 20 mg/ml",
    "MetoCloPramid 5 mg/ml",
    "Vitamin K, 0,4 mg/ml",
    "Enoximon 2 mg/ml",
    "Thiamin",
    "cloNIDin 750µg/50ml",
    "Cotrimoxazol 3,84 mg/ml",
    "cloNIDin 15 µg/ml",
    "Calciumchlorid",
    "Argipressin 1E/ml",
    "Kaliumphosphat 0,6 mmol/ml",
    "Dihydralazin",
    "Flucloxacillin 40 mg/ml",
    "Daptomycin 15 mg/ml",
    "CO_Bilanz_Ausfuhr_Reflux",
    "Glukose 5%",
    "Magnesium",
    "HYDROmorphon 0,2 mg/ml",
    "Humaninsulin",
    "Ondansetron, 4 mg/2ml",
    "Glyceroltrinitr",
    "Dalteparin",
    "Kaliumcanrenoat 20 mg/ml",
    "Tranexamsäure 100mg/ml",
    "Magnesiumsulfat 10%, 100 mg/ml",
    "cloNIDin 150 µg/ml",
    "Haloperidol 0,5 mg/ml",
    "Cefepim",
    "Heparin",
    "Voriconazol 2 mg/ml",
    "Norepinephrin 10mg/50ml",
    "Kaliumchlorid 7",
    "Macrogol (Klean-Prep)",
    "Mivacurium",
    "Cernevit",
    "Methylprednisolon 250mg/10ml",
    "Atropin",
    "Enoximon",
    "Cefazolin 40 mg/ml",
    "Meronem",
    "Clindamycin",
    "Suxamethonium",
    "Lormetazepam 0,2 mg/ml",
    "Haloperidol 1 mg/ml",
    "Lorazepam",
    "LORazepam 0,2mg/ml",
    "Macrogol (Movicol)",
    "dihydrALAZIN 2 mg/ml",
    "levETIRAcetam 10 mg/ml",
    "Citalopram",
    "Paracetamol",
    "Parecoxib",
    "Propofol 1% 10 mg/ml",
    "Droperidol",
    "Cimetidin",
    "Diazepam 5 mg/ml",
    "Physostigminsal",
    "Tranexamsäure",
    "Natriumhydrogenkarbonat",
    "Clindamycin 12 mg/ml",
    "Magnesiumsulfat 10mg/ml",
    "Indocyaningrün",
    "Nutrison Advanced Peptisorb 500ml 8 Btl.",
    "Natriumbicarbonat",
    "Kalziumchlorid",
    "Lidocain",
    "Imipenem+Cilastatin",
    "Ciprofloxacin 2 mg/ml",
    "Aztreonam 20 mg/ml",
    "Tigecyclin 100mg/50ml",
    "Epinephrin",
    "Fosfomycin",
    "Neostigmin 0,5 mg/ml",
    "Thrombozytenkonzentrat, Apherese-",
    "Ephedrin",
    "Argatroban 1mg/ml",
    "Magnesiumsulfat",
    "Neostigmin 0,01 mg/ml",
    "Morphinsulfat 10 mg/10 ml",
    "Magnesium 5-Sulfat",
    "prednisoLON 2mg/ml",
    "Glucose (G10) 100mg/ml",
    "Imipenem+Cilastatin 1000+1000mg/200ml",
    "Norepinephrin 60µg/ml",
    "levETIRAcetam 100 mg/ml",
    "Caspofungin",
    "GlycerolTriNitrat 1mg/ml",
    "MetoCloPramid+Neostigmin 60mg+3mg",
    "Thrombozytenkonzentrat",
    "Prednisolon",
    "Na-thiosulfat_25%",
    "Argatroban 50mg/50ml",
    "Diazepam 10mg/ml",
    "Terlipressin 0,85mg/8,5ml",
    "Methylprednisol",
    "Landiolol 6mg/ml",
    "Levofloxacin 5 mg/ml",
    "Fresubin Hepa N",
    "Metoprolol 1 mg/ml",
    "Hydrocortison",
    "Thiopental",
    "Glyzeroltrinitrat",
    "Linezolid",
    "Fresubin HP 2 kcal/ml",
    "Ambroxol 20 mg/ml",
    "Di-/Natriumhydrogen",
    "Simeticon",
    "G 10",
    "Trometamol (TRIS)",
    "Dimetindenmaleat 1 mg/ml",
    "Calciumgluconat 10%",
    "Natriumcitrat_4%",
    "Natriumthiosulfat 10% 100 mg/ml",
    "aMIOdaron 6 mg/ml",
    "Dexmedetomidin",
    "Cefazolin",
    "Methylenblau",
    "Ceftriaxon 1 g/50 ml",
    "Antithrombin III 50 IE/ml",
    "Gerinnungsfaktoren II/VII/IX/X",
    "Cefotaxim 40 mg/ml",
    "Levosimendan 12,5 mg / 250 ml G5%",
    "Natriumhydrogen",
    "Erythrozytenkonzentrat 310 ml",
    "Metoclopramid",
    "Humaninsulin normal 100IE/50ml",
    "Risperidon 1mg/ml",
    "Flucloxacillin",
    "Metoprolol",
    "Glukose",
    "G 20",
    "Glucose (G50) 500mg/ml",
    "Daptomycin 10 mg/ml",
    "Ketamin",
    "Magnesiumsulfat 20mg/ml",
    "Ciprofloxacin",
    "Fosaprepitant",
    "Ceftriaxon",
    "Spironolacton",
    "Trometamol 1 mmol/ml",
    "Vancomycin 5 mg/ml",
    "Vecuronium",
    "DimenhyDRINAT 62 mg",
    "Natriumchlorid 5,85% 1mmol/ml",
    "DimenhyDRINAT 6,2 mg/ml",
    "Rocuroniumbromi",
    "Lormetazepam",
    "Fibrinogen",
    "Clarithromycin 2 mg/ml",
    "Cafedrin+Theodrenalin (21 mg/ml) (Akrinor)",
    "Gelatine",
    "Erythrozytenkonzentrat bestr.  310 ml",
    "ROCuronium 10 mg/ml",
    "Faktor II/VII/I",
    "aMIOdaron 3 mg/ml",
    "Insulin Actraphane 100IE/ml",
    "Methylpredinisolon",
    "Ondansetron, 8 mg/4ml",
    "Amiodaron",
    "Ceftriaxon 2 g/50 ml",
    "Moxifloxazin",
    "Phytomenadion VitK 10 mg/ml",
    "Naloxon 40 µg/ml",
    "Mannitol",
    "Lacosamid 0,8mg/ml",
    "levETIRAcetam 150 mg/ml",
    "Dexmedetomidin 800µg/50ml",
    "Fortimel Energy 1,5 kcal/ml",
    "Voriconazol 4 mg/ml",
    "Melperon 5mg/ml",
    "Pipamperon 4 mg/ml",
    "Natriumpicosulfat",
    "Diazepam 1 mg/ml",
    "Ibandronsäure",
    "Methylprednisolon 500mg/10ml",
    "Vollelektrolytlösung + Magnesium 4,05 mmol",
    "Patient_ITS_Dialyse_Einfuhr",
    "Norepinephrin 1000µg/ml",
    "Tranexamsäure 20 mg/ml",
    "Desmopressin 0,4µg/ml",
    "Phytomenadion 0,4 mg/ml",
    "Tobramycin 1,6 mg/ml",
    "Calciumgluconat",
    "Methylnaltrexonium",
    "Wasser für",
    "Lormetazepam 0,04 mg/ml",
    "NaCl 0,9% 500 m",
    "Thrombozytenkonzentrat, Pool- ",
    "Thrombozytenkonzentrat, bestr.",
    "Vollelektrolytlösung",
    "Vitamin K1 (Phytomenadion)",
    "Nitroprussidnatrium 1mg/ml",
    "Clarithromycin",
    "Polystyroldivinylbenzolsulfonsäure (Resonium)",
    "MetoCloPramid+Neostigmin 90mg+4,5mg",
    "Phytomenadion VitK 0,2 mg/ml",
    "Fosfomycin 50 mg/ml",
    "Trometamol (TRIS) 60mmol/40ml peripher",
    "Haloperidol 2 mg/ml",
    "Ganciclovir 10 mg / ml",
    "Vitamin K, 10 mg/ml",
    "Magnesiumaspart",
    "DEXAmethason 4 mg/ml",
    "Metoclopramid+Neostigmin",
    "Basiliximab",
    "aMIOdaron 50 mg/ml",
    "Indozyaningrün (ICG)",
    "Methylprednisolon 1000mg/10ml",
    "Immunglobulin 0,1g/ml",
    "Cafedrin+Theodrenalin_200/10mg",
    "Haloperidol",
    "Pethidin",
    "Insulin(Normal) 100 i.E./ml",
    "Antithrombin III",
    "Ambroxol 3mg/ml",
    "Flumazenil",
    "Fludarabin",
    "Fresubin_Soya",
    "Vitamin K 10 mg/ml",
    "Aztreonam",
    "Dobutamin",
    "Tigecyclin 2 mg/ml",
    "Ceftazidim",
    "Mannitol 20%, 200 mg/ml",
    "Fluorescein",
    "Hepatitis-B-Ig",
    "Digitoxin 0,001 mg/ml",
    "Magnesiumsulfat 2mg/ml",
    "Prothrombinkomplex (PPSB)",
    "Natriumphosphat",
    "Plasma, lyophilisiertes Human- ",
    "Oxytocin",
    "Glycopyrronium 0,2 mg/ml",
    "Clemastin",
    "CO_Bilanz_Ausfuhr_Punktion",
    "Gentamicin 200mg/50ml",
    "Cyanocobalamin",
    "ASS 2mg/ml",
    "Protamin",
    "Promethazin",
    "ASS 50 mg/ml",
    "Parecoxib 4mg/ml",
    "Natriumperchlor",
    "Fortimel Jucy 1,5 kcal/ml",
    "Esmolol",
    "LORazepam 2 mg/ml",
    "Prednisolon 100mg/10ml",
    "LORazepam",
    "Tobramycin 4,2 mg/ml",
    "methylPREDNISolon 2mg/ml",
    "Pasireotid",
    "Valproinsäure 600mg/250ml",
    "Erythropoetin b",
    "DEXAmethason 0,8mg/ml",
    "Gentamicin 5 mg/ml",
    "Digitoxin",
    "Remdesivir 0,8mg/ml",
    "prednisoLON 1mg/ml",
    "esKETAmin 25mg/ml",
    "Azithromycin 500mg/250ml",
    "Remdesivir 0,4 mg/ml",
    "Phenytoin",
    "KETAmin 50 mg/ml",
    "Thiamazol",
    "Adenosin",
    "Midazolam 5 mg/ml",
    "VitaminK 10 mg/ml",
    "Ioxitalaminsäur",
    "Loperamid ",
    "Ertapenem",
    "Cotrimoxazol 7,68 mg/ml",
    "Atropin 0,5 mg/ml",
    "Ampicillin 80 mg/ml",
    "Phenylephrin",
    "Faktor XIII",
    "Metamizol 500 mg/50 ml",
    "Ranitidin",
    "Glucagon",
    "Na-thiosulfat_10%",
    "Physostigmin",
    "Naloxon 0,4 mg/ml",
    "Colistin 3 MioIE/50ml",
    "Lactulose",
    "Ursodeoxycholsäure",
    "HYDROmorphon",
    "G 40",
    "prednisoLON 50 mg/ml",
    "Fortimel Jucy 2",
    "Levothyroxin",
    "Methylthioninium",
    "Alfentanil",
    "Glycopyrroniumb",
    "Nitrendipin",
    "Folsäure",
    "Acetazolamid",
    "Tracutil",
    "Insulin (human)",
    "Levetiracetam",
    "Vitamin K, 0,2 mg/ml",
    "Mannitol 15%, 150 mg/ml",
    "Daptomycin",
    "clonazePAM 0,2mg/ml",
    "Thiamazol (40 mg/ml)",
    "EPINEPHrin 100 µg/ml",
    "Hydrokortison 50mg/ml",
    "Valproinsäure",
    "prednisoLON 100 mg/ml",
    "Tramadol",
    "Orciprenalin",
]
