#!/bin/bash
#SBATCH --job-name=note_embeddings
#SBATCH --output=logs/text_embedding_%j.log
#SBATCH --error=logs/text_embedding_%j.log
#SBATCH --cpus-per-task=16
#SBATCH --mem=100G
#SBATCH --partition=compute # -p
#SBATCH --time=24:00:00
#SBATCH -o logs/data_segmentation.out

source /etc/profile.d/conda.sh

eval "$(conda shell.bash hook)"
conda activate note_embeddings
export TQDM_DISABLE=1

#datasets=("nwicu" "ehrshot" "aumcdb")
#for dataset in "${datasets[@]}"; do
#  echo "Processing dataset: $dataset"
#  python get_embeddings.py \
#    --data-path="/sc-projects/sc-proj-cc08-cassandra/RW_Clinical_Notes/datasets/codes/${dataset}_unique_codes.parquet" \
#    --output-path="/sc-projects/sc-proj-cc08-cassandra/RW_Clinical_Notes/datasets/codes/${dataset}_unique_codes_embeddings.parquet" \

python get_embeddings.py \
--data-path=/sc-projects/sc-proj-cc08-cassandra/RW_Clinical_Notes/datasets/codes/nwicu_unique_codes.parquet \
--output-path=/sc-projects/sc-proj-cc08-cassandra/RW_Clinical_Notes/datasets/codes/nwicu_unique_codes_embeddings.parquet \
--text-columns description

python get_embeddings.py \
--data-path=/sc-projects/sc-proj-cc08-cassandra/RW_Clinical_Notes/datasets/codes/aumcdb_unique_codes.parquet \
--output-path=/sc-projects/sc-proj-cc08-cassandra/RW_Clinical_Notes/datasets/codes/aumcdb_unique_codes_embeddings.parquet \
--text-columns code \


#
